### ISSUE TITLE
Error when using --remove option

### ISSUE THREAD

**Issue by quovadimus** [jssimporter/Spruce#14] opened 2016-02-01 16:27 UTC
Hoping you may be able to provide some insight on an error I'm getting when I attempt to use the --remove option with an xml file.  This is what I'm seeing:

```
computername:~ username$ ~/Desktop/spruce.py --remove ~/Desktop/test3.xml 
Are you sure you want to continue deleting objects from https://jssaddress.company.com? (Y or N): y
ComputerGroup object 999: Name of a Computer Group deleted.
Traceback (most recent call last):
  File "/Users/username/Desktop/spruce.py", line 1949, in <module>
    main()
  File "/Users/username/Desktop/spruce.py", line 1943, in main
    remove(removal_tree)
  File "/Users/username/Desktop/spruce.py", line 1873, in remove
    if item.tag in needs_file_removal and file_type_removals:
UnboundLocalError: local variable 'needs_file_removal' referenced before assignment
```

It results in the first item in the list being removed and then stopping with the above error.

Thanks!

**Comment by kitzy** [comment] 2016-02-01 21:05
I'm seeing identical behavior.

ComputerGroup object 28: Microsoft Outlook - Update deleted.
Traceback (most recent call last):
  File "/Users/username/Desktop/spruce.py", line 1931, in <module>
    main()
  File "/Users/username/Desktop/spruce.py", line 1925, in main
    remove(removal_tree)
  File "/Users/username/Desktop/spruce.py", line 1873, in remove
    if item.tag in needs_file_removal and file_type_removals:
UnboundLocalError: local variable 'needs_file_removal' referenced before assignment

**Comment by homebysix** [comment] 2016-06-06 18:10
Yes, I'm seeing this too. I actually think it may be the same root cause as #15, because in both cases the failure happens after the first object is removed.

**Comment by sheagcraig** [comment] 2016-06-06 19:07
Uh oh! Thanks for the input folks. I'll take a look at this soon. I'm sure it's some poor coding on my part that `needs_file_removal` can get to that line without existing. If anyone wants to send a PR, that would definitely get it fixed even quicker!

**Comment by homebysix** [comment] 2016-06-08 17:29
Ask and ye shall receive.

**Comment by sheagcraig** [comment] 2016-07-01 19:54
Those folks on this issue, can we close this now?

**Comment by sheagcraig** [comment] 2016-07-01 19:57
So the reason this is broken is because that version downloads as a DMG with a non-flat package as the contents.

As this is a historical version, I'm not sure we really need to create a separate recipe just for the 14.1.0, although perhaps you disagree. I'm going to assume you're fine with closing this and do so, just for efficiency's sake; but if you want me to carve out a 14.1.0 recipe, let me know.

**Comment by homebysix** [comment] 2016-07-01 20:58
OK to close.

**Closed as completed** 2016-07-01 23:56 UTC
