### ISSUE TITLE
Don't show policies generated by Jamf Remote

### ISSUE THREAD

**Issue by everetteallen** [jssimporter/Spruce#8] opened 2015-08-25 21:11 UTC
I am seeing return from spruce -v --policies that look like:
`2014-02-27 at 8:31 PM | casmit14 | 1 Computer
2014-02-27 at 8:34 PM | casmit14 | 1 Computer
2014-02-27 at 8:43 PM | casmit14 | 1 Computer
2014-03-13 at 5:52 PM | djgreen | 4 Computers
2014-03-13 at 5:56 PM | djgreen | 6 Computers
2014-05-21 at 3:23 PM | rjblanke | 1 Computer`
followed by "normal" .  So looks like of like this:

`/Desktop/Spruce-testing/spruce.py --policies -v 
🌲  Policies not Scoped (369)
    2015-08-19 at 12:43 PM | mortonwd | 1 Computer
        ... 100's more with date time stamp
    Acrobat Pro Test Install
    Adobe CS6 Design Standard
    Adobe-Premiere-CS6
`
Of course none of our policies are named with time/date.
This very odd did I miss a feature?

**Comment by homebysix** [comment] 2015-08-25 21:14
@everetteallen Do you use Casper Remote? (Or rather, do casmit14, djgreen, and rjblanke use Casper Remote?)

I suspect those policies are the leftovers from previous sessions. JAMF doesn't expose them on the web UI, but they're accessible via the API.

**Comment by everetteallen** [comment] 2015-08-25 21:15
I do not.  djgreen does not, casmit14 and rjblanke have but not lately.

**Comment by everetteallen** [comment] 2015-08-25 21:19
For the record I have 267.  Wonder how those get flushed...

**Comment by homebysix** [comment] 2015-08-25 21:23
I nuked mine with a `curl ... -X DELETE` a while ago. No ill effects, but proceed at your own risk.
https://bryson3gps.wordpress.com/the-unofficial-jss-api-docs/#sample-code-shell-scripts

**Comment by sheagcraig** [comment] 2015-08-26 12:30
This is on the feature list for spruce to handle too.

**Comment by aarondavidpolley** [comment] 2020-02-13 22:41
Just adding to this/confirming that in Jamf Pro 10.18.0 and Spruce-3.0.0b5 "ghost" policy records created by Casper/Jamf Remote still exist and cause false positives in the reporting

**Comment by aarondavidpolley** [comment] 2020-02-13 22:42
Also @grahampugh this appears to be a dupe of issue #4

**Comment by grahampugh** [comment] 2020-02-13 22:53
Good shout. Closing since dupe of #4 (lowest wins!)

**Closed as completed by grahampugh** 2020-02-13 22:53 UTC
Labels: enhancement, help wanted
